CREATE DATABASE DB_PIZZARIA_LEGAL;
USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS( ID BIGINT(5) AUTO_INCREMENT,
TIPO VARCHAR(255) NOT NULL,
DELIVERY VARCHAR(255),
PRIMARY KEY (ID));

CREATE TABLE TB_PIZZAS( ID BIGINT(5) AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
INGREDIENTES VARCHAR(255) NOT NULL,
PRECO DECIMAL (6,2) NOT NULL,
TAMANHO VARCHAR(255) NOT NULL,
CATEGORIAS_ID BIGINT(5),
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);

INSERT INTO TB_CATEGORIAS(TIPO,DELIVERY)
VALUES ("PIZZAS VEGANAS", "SIM");

INSERT INTO TB_CATEGORIAS(TIPO,DELIVERY)
VALUES ("PIZZAS DOCES", "SIM");

INSERT INTO TB_CATEGORIAS(TIPO,DELIVERY)
VALUES ("PIZZAS SALGADAS", "SIM");

INSERT INTO TB_CATEGORIAS(TIPO,DELIVERY)
VALUES ("PIZZAS C/ BORDA RECHEADA", "SIM");

INSERT INTO TB_CATEGORIAS(TIPO,DELIVERY)
VALUES ("PIZZA AUTORAL", "SIM");

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_PIZZAS (NOME, INGREDIENTES, PRECO, TAMANHO, CATEGORIAS_ID)
VALUES ("BROCOLIS","Massa de batata, molho de tomate, brócolis cozido", 52.00, "Grande", 1);

INSERT INTO TB_PIZZAS (NOME, INGREDIENTES, PRECO, TAMANHO, CATEGORIAS_ID)
VALUES ("MORANGUETE","Massa de trigo, chocolate ao leite derretido, morangos fatiados", 32.00, "Broto", 2);

INSERT INTO TB_PIZZAS (NOME, INGREDIENTES, PRECO, TAMANHO, CATEGORIAS_ID)
VALUES ("CALABRESA","Massa de trigo, molho de tomate, linguiça calabresa fatiada", 48.00, "Grande", 3);

INSERT INTO TB_PIZZAS (NOME, INGREDIENTES, PRECO, TAMANHO, CATEGORIAS_ID)
VALUES ("FRANCOPIRY","Massa de trigo, molho de tomate, frango desfiado e borda recheada com catupiry", 75.00, "Grande", 4);

INSERT INTO TB_PIZZAS (NOME, INGREDIENTES, PRECO, TAMANHO, CATEGORIAS_ID)
VALUES ("AUTORAL","À escolha do cliente, disponibilizar cardápio autoral", 95.00, "Grande", 5);

INSERT INTO TB_PIZZAS (NOME, INGREDIENTES, PRECO, TAMANHO, CATEGORIAS_ID)
VALUES ("QUATRO QUEIJOS","Massa de trigo, molho de tomate, mozzarela, provolone, catupiry e cheddar", 62.00, "Grande", 3);

INSERT INTO TB_PIZZAS (NOME, INGREDIENTES, PRECO, TAMANHO, CATEGORIAS_ID)
VALUES ("GRÃO DE BICO","Massa de quinoa, molho pesto, grão de bico torrado", 54.00, "Broto", 1);

INSERT INTO TB_PIZZAS (NOME, INGREDIENTES, PRECO, TAMANHO, CATEGORIAS_ID)
VALUES ("Confetti","Massa de trigo, chocolate meio amargo derretido, M&Ms coloridos salpicados", 57.00, "Grande", 2);

SELECT * FROM TB_PIZZAS WHERE PRECO > 45.00;

SELECT * FROM TB_PIZZAS WHERE PRECO > 50.00 AND PRECO < 100.00;

SELECT * FROM TB_PIZZAS WHERE NOME LIKE "M%";

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON 
TB_PIZZAS.CATEGORIAS_ID = TB_CATEGORIAS.ID;

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON 
TB_PIZZAS.CATEGORIAS_ID = 1 AND TB_CATEGORIAS.ID =1;

