CREATE DATABASE DB_RH_SERVICOS;
USE DB_RH_SERVICOS;
CREATE TABLE COLABORADORES(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
IDADE INT,
FUNCAO CHAR(255),
SALARIO INT,
PRIMARY KEY (ID)
);

INSERT INTO COLABORADORES (NOME,IDADE,FUNCAO,SALARIO)
VALUES ("Vanessa", 35, "Secretária", 2580);
INSERT INTO COLABORADORES (NOME,IDADE,FUNCAO,SALARIO)
VALUES ("Juliana Alvez", 42, "Faxineira", 1300);
INSERT INTO COLABORADORES (NOME,IDADE,FUNCAO,SALARIO)
VALUES ("Vandeilson Lopes", 58, "Manutenção", 2457);
INSERT INTO COLABORADORES (NOME,IDADE,FUNCAO,SALARIO)
VALUES ("Barbara Ortiz", 28, "Assistente de Contabilidade", 2800);
INSERT INTO COLABORADORES (NOME,IDADE,FUNCAO,SALARIO)
VALUES ("Wesley Santos", 25, "Suporte Técnico", 2600);
INSERT INTO COLABORADORES (NOME,IDADE,FUNCAO,SALARIO)
VALUES ("Vinicius Rocha", 19, "Jovem Aprendiz", 1212);

SELECT * FROM COLABORADORES WHERE SALARIO < 2000; 

SELECT * FROM COLABORADORES WHERE SALARIO > 2000;

SET SQL_SAFE_UPDATES = 0;

UPDATE COLABORADORES SET NOME = "Vanessa García" WHERE ID = 1;

SELECT * FROM COLABORADORES WHERE ID = 1;

