CREATE DATABASE DB_ECOMMERCE;
USE DB_ECOMMERCE;
CREATE TABLE PRODUTOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
PRECO INT,
COR CHAR(255),
EM_ESTOQUE INT,
FRETE_GRATIS CHAR(255),
PRIMARY KEY (ID)
);

INSERT INTO PRODUTOS (NOME, PRECO, COR, EM_ESTOQUE, FRETE_GRATIS)
VALUES ("Iphone 13", 4500, "Branco", 25, "Não");
INSERT INTO PRODUTOS (NOME, PRECO, COR, EM_ESTOQUE, FRETE_GRATIS)
VALUES ("Fone JBL", 350, "Preto", 45, "Sim");
INSERT INTO PRODUTOS (NOME, PRECO, COR, EM_ESTOQUE, FRETE_GRATIS)
VALUES ("Mouse Sem Fio", 85, "Azul", 320, "Não");
INSERT INTO PRODUTOS (NOME, PRECO, COR, EM_ESTOQUE, FRETE_GRATIS)
VALUES ("Teclado Sem Fio", 90, "Azul", 255, "Não");
INSERT INTO PRODUTOS (NOME, PRECO, COR, EM_ESTOQUE, FRETE_GRATIS)
VALUES ("Mouse Pad", 45, "Preto", 45, "Sim");
INSERT INTO PRODUTOS (NOME, PRECO, COR, EM_ESTOQUE, FRETE_GRATIS)
VALUES ("Cabo de Rede 2m", 30, "Cinza", 32, "Sim");
INSERT INTO PRODUTOS (NOME, PRECO, COR, EM_ESTOQUE, FRETE_GRATIS)
VALUES ("Ring Light Pro", 800, "Preto", 3, "Sim");
INSERT INTO PRODUTOS (NOME, PRECO, COR, EM_ESTOQUE, FRETE_GRATIS)
VALUES ("Câmera Profissional Nikon + 2 lentes", 4500, "Preta", 4, "Não");

SELECT * FROM PRODUTOS WHERE PRECO > 500;
SELECT * FROM PRODUTOS WHERE PRECO < 500;

SET SQL_SAFE_UPDATES = 0;

UPDATE PRODUTOS SET FRETE_GRATIS = "SIM" WHERE NOME = "Iphone 13";
SELECT * FROM PRODUTOS WHERE ID=1;